// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'features/music/data/models/song_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 988103931647091532),
    name: 'SongModel',
    lastPropertyId: const obx_int.IdUid(10, 833339340596564512),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4302631659182293035),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7033601461731429459),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 2465917469938816286),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 439232105517309470),
        name: 'path',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 4865795324489707485),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8040117477271467878),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1887370184956648773),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2565337979702965033),
        name: 'album',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1569501705028459955),
        name: 'duration',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 839779074879433370),
        name: 'artworkPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8150190735544892401),
        name: 'lastScannedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 833339340596564512),
        name: 'isExternal',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 988103931647091532),
    lastIndexId: const obx_int.IdUid(2, 4865795324489707485),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SongModel: obx_int.EntityDefinition<SongModel>(
      model: _entities[0],
      toOneRelations: (SongModel object) => [],
      toManyRelations: (SongModel object) => {},
      getId: (SongModel object) => object.obxId,
      setId: (SongModel object, int id) {
        object.obxId = id;
      },
      objectToFB: (SongModel object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final pathOffset = fbb.writeString(object.path);
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        final albumOffset = object.album == null
            ? null
            : fbb.writeString(object.album!);
        final durationOffset = object.duration == null
            ? null
            : fbb.writeString(object.duration!);
        final artworkPathOffset = object.artworkPath == null
            ? null
            : fbb.writeString(object.artworkPath!);
        fbb.startTable(11);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, pathOffset);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, artistOffset);
        fbb.addOffset(5, albumOffset);
        fbb.addOffset(6, durationOffset);
        fbb.addOffset(7, artworkPathOffset);
        fbb.addInt64(8, object.lastScannedAt.millisecondsSinceEpoch);
        fbb.addBool(9, object.isExternal);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final albumParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final durationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final artworkPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final lastScannedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final isExternalParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final object = SongModel(
          obxId: obxIdParam,
          id: idParam,
          path: pathParam,
          title: titleParam,
          artist: artistParam,
          album: albumParam,
          duration: durationParam,
          artworkPath: artworkPathParam,
          lastScannedAt: lastScannedAtParam,
          isExternal: isExternalParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SongModel] entity fields to define ObjectBox queries.
class SongModel_ {
  /// See [SongModel.obxId].
  static final obxId = obx.QueryIntegerProperty<SongModel>(
    _entities[0].properties[0],
  );

  /// See [SongModel.id].
  static final id = obx.QueryStringProperty<SongModel>(
    _entities[0].properties[1],
  );

  /// See [SongModel.path].
  static final path = obx.QueryStringProperty<SongModel>(
    _entities[0].properties[2],
  );

  /// See [SongModel.title].
  static final title = obx.QueryStringProperty<SongModel>(
    _entities[0].properties[3],
  );

  /// See [SongModel.artist].
  static final artist = obx.QueryStringProperty<SongModel>(
    _entities[0].properties[4],
  );

  /// See [SongModel.album].
  static final album = obx.QueryStringProperty<SongModel>(
    _entities[0].properties[5],
  );

  /// See [SongModel.duration].
  static final duration = obx.QueryStringProperty<SongModel>(
    _entities[0].properties[6],
  );

  /// See [SongModel.artworkPath].
  static final artworkPath = obx.QueryStringProperty<SongModel>(
    _entities[0].properties[7],
  );

  /// See [SongModel.lastScannedAt].
  static final lastScannedAt = obx.QueryDateProperty<SongModel>(
    _entities[0].properties[8],
  );

  /// See [SongModel.isExternal].
  static final isExternal = obx.QueryBooleanProperty<SongModel>(
    _entities[0].properties[9],
  );
}
